<?php

namespace ACSEO\Bundle\MyRunningPlannerBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use ACSEO\Bundle\MyRunningPlannerBundle\Entity\User;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadUserData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new User()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new User();
        $item1->setEmail(<<<'EOT'
matthieu.cutin@acseo-conseil.fr
EOT
);
        $item1->setPlainPassword(NULL);
        $item1->setName(<<<'EOT'
Matthieu
EOT
);
        $item1->setUsername(<<<'EOT'
matthieu.cutin@acseo-conseil.fr
EOT
);
        $item1->setUsernameCanonical(<<<'EOT'
matthieu.cutin@acseo-conseil.fr
EOT
);
        $item1->setEmailCanonical(<<<'EOT'
matthieu.cutin@acseo-conseil.fr
EOT
);
        $item1->setEnabled(1);
        $item1->setPassword(<<<'EOT'
$2y$13$bn5ei53wikg08gc0wckgguv7zD3nIz7nnKzlDfL/249RSlEdiuUS6
EOT
);
        $item1->setLastLogin(new \DateTime("2016-04-26 11:00:21"));
        $item1->setConfirmationToken(NULL);
        $item1->setPasswordRequestedAt(NULL);
        $item1->setLocked(0);
        $item1->setExpired(0);
        $item1->setExpiresAt(NULL);
        $item1->setRoles(unserialize('a:0:{}'));
        $item1->setCredentialsExpired(0);
        $item1->setCredentialsExpireAt(NULL);

        $this->addReference('_reference_User_1', $item1);

        $manager->persist($item1);


        $manager->flush();
    }

}
