<?php

namespace ACSEO\Bundle\MyRunningPlannerBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use ACSEO\Bundle\MyRunningPlannerBundle\Entity\Race;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadRaceData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Race()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item2 = new Race();
        $item2->setAscension(100);
        $item2->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item2->setDistance(10);
        $item2->setName(<<<'EOT'
Course 1
EOT
);
        $item2->setRunner($this->getReference('_reference_User_1'));
        $item2->setRanking(NULL);

        $this->addReference('_reference_Race_2', $item2);

        $manager->persist($item2);

        $item3 = new Race();
        $item3->setAscension(100);
        $item3->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item3->setDistance(10);
        $item3->setName(<<<'EOT'
Course 2
EOT
);
        $item3->setRunner($this->getReference('_reference_User_1'));
        $item3->setRanking(NULL);

        $this->addReference('_reference_Race_3', $item3);

        $manager->persist($item3);

        $item4 = new Race();
        $item4->setAscension(100);
        $item4->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item4->setDistance(10);
        $item4->setName(<<<'EOT'
Course 3
EOT
);
        $item4->setRunner($this->getReference('_reference_User_1'));
        $item4->setRanking(NULL);

        $this->addReference('_reference_Race_4', $item4);

        $manager->persist($item4);

        $item5 = new Race();
        $item5->setAscension(100);
        $item5->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item5->setDistance(10);
        $item5->setName(<<<'EOT'
Course 4
EOT
);
        $item5->setRunner($this->getReference('_reference_User_1'));
        $item5->setRanking(NULL);

        $this->addReference('_reference_Race_5', $item5);

        $manager->persist($item5);

        $item6 = new Race();
        $item6->setAscension(100);
        $item6->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item6->setDistance(10);
        $item6->setName(<<<'EOT'
Course 5
EOT
);
        $item6->setRunner($this->getReference('_reference_User_1'));
        $item6->setRanking(NULL);

        $this->addReference('_reference_Race_6', $item6);

        $manager->persist($item6);

        $item7 = new Race();
        $item7->setAscension(100);
        $item7->setDate(new \DateTime("2016-05-26 17:00:00"));
        $item7->setDistance(10);
        $item7->setName(<<<'EOT'
Course 6
EOT
);
        $item7->setRunner($this->getReference('_reference_User_1'));
        $item7->setRanking(NULL);

        $this->addReference('_reference_Race_7', $item7);

        $manager->persist($item7);


        $manager->flush();
    }

}
