acseo_my_running_planner:
    resource: "@ACSEOMyRunningPlannerBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "."
    type:     "api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"
