services:
    resource.user:
        parent:    "api.resource"
        arguments: [ 'ACSEO\Bundle\MyRunningPlannerBundle\Entity\User' ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "user_read" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "user_write" ] } ]
        tags:      [ { name: "api.resource" } ]
